name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: sonar-scanner
      uses: Warchant/setup-sonar-scanner@v1
      with:
        # Sonar-scanner version
        version: 4.2.0.1873  
    - name: Build & Push to GitHub Package
      uses: opspresso/action-docker@master
      env:
        USERNAME: ${{ secrets.GITHUB_USERNAME }}
        PASSWORD: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
        REGISTRY: "docker.pkg.github.com"
        # IMAGE_NAME: "user_id/image_name"
        TAG_NAME: "v0.0.1"
        LATEST: "true"

